### ISSUE TITLE
divide by zero

### ISSUE THREAD

**Issue by prescottbreeden** [prescottbreeden/ultimate_fan_project#11]
current behavior: when loading quiz stats - occasionally django throws a divide by zero error (see below)

File "/code/codingDojo/python/django/ultimate_fan_project/apps/quiz/views.py" in quiz_stats
  69. 			int(100*len(Quiz.objects.filter(user= user, score= '1')) / len(Quiz.objects.filter(user = user))) ]

Exception Type: ZeroDivisionError at /quiz/quiz_stats
Exception Value: division by zero

desired behavior: if this is to be expected in certain circumstances, have a handler to route a user appropriately.  otherwise simply correct issue.

**Comment by prescottbreeden** [comment]
Looking into the code, I feel like this will only happen is somehow the code is firing without a user in session, so this bug may be really hard to replicate

**Comment by sjsilverstein** [comment]
Found the bug. Issue with leaderboard when a new user visits the board without having taken any tests. Bug fixed.
